version: 2.1

# circle job definition for poetry install
jobs:
  build:
    docker:
      - image: cimg/python:3.11.4
    steps:
      - checkout
      - run:
          name: Install Poetry
          command: |
            curl -sSL https://install.python-poetry.org | python3 -
      - run:
          name: Install dependencies
          command: |
            poetry install
      - run:
          name: Run tests
          command: |
            poetry run python -m pytest -s tests/

# circle workflow definition
workflows:
  build_and_test:
    jobs:
      - build